- name: "configuration play" 
  hosts: frontendserver
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root  
  environment:
    AWS_ACCESS_KEY_ID: "{{lookup('ansible.builtin.env','AWS_ACCESS_KEY_ID')}}"
    AWS_SECRET_ACCESS_KEY: "{{lookup('ansible.builtin.env','AWS_SECRET_ACCESS_KEY')}}"
    AWS_REGION: "{{lookup('ansible.builtin.env','AWS_REGION')}}"

  roles:
    - run-container
  