---

# - name: "download aws-cli zip"
#   ansible.builtin.shell: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"

# - name: "install unzip"
#   ansible.builtin.apt:
#     name: unzip
#     state: present

# - name: "check if aws-cli exist in /bin"
#   ansible.builtin.stat:
#     path: /usr/local/aws-cli
#   register: aws

# - name: "unzip aws-cli"
#   ansible.builtin.shell: unzip awscliv2.zip

# - name: "run aws install script"
#   ansible.builtin.shell: sudo ./aws/install 
#   when: not aws.stat.exists

# - name: "install aws-cli to /bin and /local directories"
#   ansible.builtin.shell: ./aws/install -i /usr/local/aws-cli -b /usr/local/bin 
#   when: not aws.stat.exists
- name: "uninstall old docker-ce"
  ansible.builtin.shell:  sudo apt-get remove docker docker-engine docker.io containerd runc

- name: "install more latest docker"
  ansible.builtin.shell: sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin

- name: "start docker engine"
  ansible.builtin.shell: sudo systemctl start docker  

- name: "login to aws ecr"
  ansible.builtin.shell: aws ecr get-login-password --region $AWS_REGION | \
            docker login --username AWS \
            --password-stdin 072056452537.dkr.ecr.us-east-1.amazonaws.com

- name: "Pull in image from ECR"
  ansible.builtin.shell: docker pull 072056452537.dkr.ecr.us-east-1.amazonaws.com/hello-java:v1.0.0

- name: "run docker container"
  ansible.builtin.shell: docker run 072056452537.dkr.ecr.us-east-1.amazonaws.com/hello-java:v1.0.0
...