---
                 
- name: "install latest docker"
  ansible.builtin.yum:
    name: docker
    state: latest

- name: "start docker engine"
  ansible.builtin.shell: systemctl start docker

- name: "login to aws ecr"
  ansible.builtin.shell: aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin "${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"

- name: "Pull in image from ECR"
  ansible.builtin.shell: docker pull "${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_TAG}"

- name: "run docker container"
  ansible.builtin.shell: docker run -p 8080:8080 "${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_TAG}""
...